version: '3.8'

services:
  flask-app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    networks:
      - monitoring-network
    restart: unless-stopped

  prometheus:
    build:
      context: ./prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring-network
    volumes:
      - prometheus-data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring-network
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/dashboards/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped

networks:
  monitoring-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data: